spring:
  jackson:
    serialization:
      indent_output: true
  devtools:
    livereload:
      port: 35730
  cache:
    jcache:
      config: classpath:ehcache.xml

feign:
  client:
    config:
      gw2:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    root: INFO
    bot: DEBUG
    org:
      springframework:
        web: INFO